name: architecture_designed
description: Learning design architecture in Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^8.0.2
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  connectivity_plus: ^4.0.1
  get_it: ^7.6.0
  intl: 0.18.0
  flutter_svg: ^2.0.7
  bloc: ^8.1.2
  google_fonts:
  logger: ^1.4.0
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  http: ^0.13.0
  flutter_animate: ^4.2.0
  font_awesome_flutter: ^10.4.0
  lottie: ^2.4.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.3.1
  retrofit_generator: '>=5.0.0 <6.0.0'
  freezed: ^2.3.5


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/vectors/
    - assets/images/rasters/
    - assets/lotties/

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

