name: architecture_designed
description: Learning design architecture in Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^8.0.2
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  connectivity_plus:
  get_it: ^7.6.0
  intl: 0.18.0
  flutter_svg: ^2.0.7
  bloc: ^8.1.2
  google_fonts: ^5.0.0
  logger: ^1.4.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.3.1
  retrofit_generator: '>=5.0.0 <6.0.0'
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/vectors/

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

